using System.Text;
using System.Threading;
using TinyFlags.SourceGen.Generation.Planning;
using TinyFlags.SourceGen.Model;

namespace TinyFlags.SourceGen.Generation.Emission;

internal sealed class FeatureAccessEmitter
{
    public string Emit(FeatureAccessPlan plan, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        var hasNamespace = plan.Provider.NamespaceName.Length > 0;
        if (hasNamespace)
        {
            source.Append("namespace ").AppendLine(plan.Provider.NamespaceName);
            source.AppendLine("{");
        }

        WriteClass(source, plan, hasNamespace ? "    " : string.Empty, cancellationToken);

        if (hasNamespace)
        {
            source.AppendLine("}");
        }

        return source.ToString();
    }

    private static void WriteClass(
        StringBuilder source,
        FeatureAccessPlan plan,
        string indent,
        CancellationToken cancellationToken)
    {
        source.Append(indent).Append("public sealed class ").AppendLine(plan.ClassName);
        source.Append(indent).AppendLine("{");
        var memberIndent = indent + "    ";
        source.Append(memberIndent).Append("private readonly global::TinyFlags.FeatureValues ")
            .Append(plan.FieldName).AppendLine(";");
        source.AppendLine();
        WriteConstructor(source, plan, memberIndent);

        foreach (var feature in plan.Provider.Features)
        {
            cancellationToken.ThrowIfCancellationRequested();
            source.AppendLine();
            WriteProperty(source, plan, feature, memberIndent);
        }

        source.Append(indent).AppendLine("}");
    }

    private static void WriteConstructor(StringBuilder source, FeatureAccessPlan plan, string indent)
    {
        source.Append(indent).Append("public ").Append(plan.ClassName)
            .AppendLine("(global::TinyFlags.FeatureValues values)");
        source.Append(indent).AppendLine("{");
        source.Append(indent).Append("    this.").Append(plan.FieldName)
            .AppendLine(" = values ?? throw new global::System.ArgumentNullException(nameof(values));");
        source.Append(indent).AppendLine("}");
    }

    private static void WriteProperty(
        StringBuilder source,
        FeatureAccessPlan plan,
        FeatureDefinition feature,
        string indent)
    {
        var isBoolean = feature.Kind == FeatureValueKind.Boolean;
        source.Append(indent).Append("public ");
        if (HidesObjectMember(feature.Name))
        {
            source.Append("new ");
        }

        source.Append(isBoolean ? "bool" : "string").Append(" @").Append(feature.Name)
            .Append(" => this.").Append(plan.FieldName)
            .Append(isBoolean ? ".GetBoolean(" : ".GetString(");
        FeatureLiteralWriter.WriteString(source, feature.Key);
        source.Append(", ");
        FeatureLiteralWriter.WriteDefaultValue(source, feature.Kind, feature.DefaultValue);
        source.AppendLine(");");
    }

    private static bool HidesObjectMember(string name)
    {
        return name is "Equals" or "GetHashCode" or "GetType" or "ToString"
            or "ReferenceEquals" or "MemberwiseClone" or "Finalize";
    }
}
