using System.Globalization;
using System.Text;
using System.Threading;
using TinyFlags.SourceGen.Generation.Planning;
using TinyFlags.SourceGen.Model;

namespace TinyFlags.SourceGen.Generation.Emission;

internal sealed class FeatureCatalogEmitter
{
    public string Emit(FeatureCatalogPlan plan, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace TinyFlags.Generated");
        source.AppendLine("{");
        source.AppendLine("    internal static class ThisAssemblyFeatureCatalog");
        source.AppendLine("    {");
        source.AppendLine("        internal static global::System.Collections.Generic.IReadOnlyList<global::TinyFlags.FeatureDefinition> Definitions { get; } =");
        source.AppendLine("            global::System.Array.AsReadOnly(new global::TinyFlags.FeatureDefinition[]");
        source.AppendLine("            {");

        foreach (var feature in plan.Features)
        {
            cancellationToken.ThrowIfCancellationRequested();
            WriteDefinition(source, feature);
        }

        source.AppendLine("            });");
        source.AppendLine();
        WriteModuleInitializer(source);
        source.AppendLine();
        WriteRegistrations(source, plan, cancellationToken);
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static void WriteModuleInitializer(StringBuilder source)
    {
        source.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        source.AppendLine("        internal static void Initialize()");
        source.AppendLine("        {");
        source.AppendLine("            global::TinyFlags.TinyFlagsBootstrap.AddContribution(typeof(ThisAssemblyFeatureCatalog), Definitions, Register);");
        source.AppendLine("        }");
    }

    private static void WriteRegistrations(StringBuilder source, FeatureCatalogPlan plan, CancellationToken cancellationToken)
    {
        source.AppendLine("        private static void Register(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("        {");
        foreach (var className in plan.AccessClassNames)
        {
            cancellationToken.ThrowIfCancellationRequested();
            source.Append("            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::")
                .Append(className).AppendLine(">(services,");
            source.Append("                static provider => new global::").Append(className).AppendLine("(");
            source.AppendLine("                    global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::TinyFlags.FeatureValues>(provider)));");
        }
        source.AppendLine("        }");
    }

    private static void WriteDefinition(StringBuilder source, FeatureDefinition feature)
    {
        var isBoolean = feature.Kind == FeatureValueKind.Boolean;
        source.Append("                global::TinyFlags.FeatureDefinition.")
            .Append(isBoolean ? "Boolean(" : "String(");
        WriteString(source, feature.Key);
        source.Append(", ");

        if (isBoolean)
        {
            source.Append((bool)feature.DefaultValue ? "true" : "false");
        }
        else
        {
            WriteString(source, (string)feature.DefaultValue);
        }

        source.AppendLine("),");
    }

    private static void WriteString(StringBuilder source, string value)
    {
        source.Append('"');
        foreach (var character in value)
        {
            if (character == '"' || character == '\\')
            {
                source.Append('\\').Append(character);
            }
            else if (character < ' ' || character > '~')
            {
                source.Append("\\u").Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
            }
            else
            {
                source.Append(character);
            }
        }

        source.Append('"');
    }
}
